# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cart.models.cart_product_configuration_step_option import CartProductConfigurationStepOption

class TestCartProductConfigurationStepOption(unittest.TestCase):
    """CartProductConfigurationStepOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CartProductConfigurationStepOption:
        """Test CartProductConfigurationStepOption
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CartProductConfigurationStepOption`
        """
        model = CartProductConfigurationStepOption()
        if include_optional:
            return CartProductConfigurationStepOption(
                id = '',
                grn = '',
                label = cart.models.cart_localized_text.cartLocalizedText(
                    value = {
                        'key' : ''
                        }, ),
                price_variation = cart.models.cart_money.cartMoney(
                    units = '', 
                    micros = 56, ),
                weight_variation = 1.337,
                image = cart.models.option_image.OptionImage(
                    grn = '', 
                    url = '', ),
                has_quantity = True,
                quantity = 56
            )
        else:
            return CartProductConfigurationStepOption(
        )
        """

    def testCartProductConfigurationStepOption(self):
        """Test CartProductConfigurationStepOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
