# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cart.models.cart_set_payments_response import CartSetPaymentsResponse

class TestCartSetPaymentsResponse(unittest.TestCase):
    """CartSetPaymentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CartSetPaymentsResponse:
        """Test CartSetPaymentsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CartSetPaymentsResponse`
        """
        model = CartSetPaymentsResponse()
        if include_optional:
            return CartSetPaymentsResponse(
                total_due = cart.models.cart_money.cartMoney(
                    units = '', 
                    micros = 56, )
            )
        else:
            return CartSetPaymentsResponse(
        )
        """

    def testCartSetPaymentsResponse(self):
        """Test CartSetPaymentsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
