# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cart.api.basic_operations_api import BasicOperationsApi


class TestBasicOperationsApi(unittest.TestCase):
    """BasicOperationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BasicOperationsApi()

    def tearDown(self) -> None:
        pass

    def test_add_products(self) -> None:
        """Test case for add_products

        Add Products
        """
        pass

    def test_create_cart(self) -> None:
        """Test case for create_cart

        Create Cart
        """
        pass

    def test_get_active_cart_by_customer(self) -> None:
        """Test case for get_active_cart_by_customer

        Get Active Cart By Customer
        """
        pass

    def test_get_cart(self) -> None:
        """Test case for get_cart

        Get Cart
        """
        pass

    def test_list_carts(self) -> None:
        """Test case for list_carts

        List Carts
        """
        pass

    def test_merge_carts(self) -> None:
        """Test case for merge_carts

        Merge Carts
        """
        pass

    def test_remove_products(self) -> None:
        """Test case for remove_products

        Remove Products
        """
        pass

    def test_set_additional_info(self) -> None:
        """Test case for set_additional_info

        Set Additional Info
        """
        pass

    def test_set_notes(self) -> None:
        """Test case for set_notes

        Set Notes
        """
        pass

    def test_trigger_realignment(self) -> None:
        """Test case for trigger_realignment

        Trigger Realignment
        """
        pass

    def test_update_cart(self) -> None:
        """Test case for update_cart

        Update Cart
        """
        pass

    def test_update_products(self) -> None:
        """Test case for update_products

        Update Products
        """
        pass


if __name__ == '__main__':
    unittest.main()
