# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cart.models.list_carts_request_sort import ListCartsRequestSort

class TestListCartsRequestSort(unittest.TestCase):
    """ListCartsRequestSort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCartsRequestSort:
        """Test ListCartsRequestSort
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCartsRequestSort`
        """
        model = ListCartsRequestSort()
        if include_optional:
            return ListCartsRequestSort(
                evaluation_order = 56,
                field = 'UNKNOWN',
                order = 'DESC'
            )
        else:
            return ListCartsRequestSort(
        )
        """

    def testListCartsRequestSort(self):
        """Test ListCartsRequestSort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
