# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cart.models.cart_currency import CartCurrency

class TestCartCurrency(unittest.TestCase):
    """CartCurrency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCartCurrency(self):
        """Test CartCurrency"""
        # inst = CartCurrency()

if __name__ == '__main__':
    unittest.main()
