# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cart.api.promotions_api import PromotionsApi


class TestPromotionsApi(unittest.TestCase):
    """PromotionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PromotionsApi()

    def tearDown(self) -> None:
        pass

    def test_apply_coupons(self) -> None:
        """Test case for apply_coupons

        Apply Coupons
        """
        pass

    def test_remove_coupons(self) -> None:
        """Test case for remove_coupons

        Remove Coupons
        """
        pass


if __name__ == '__main__':
    unittest.main()
