# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cart.api.shipments_api import ShipmentsApi


class TestShipmentsApi(unittest.TestCase):
    """ShipmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ShipmentsApi()

    def tearDown(self) -> None:
        pass

    def test_list_shipment_methods(self) -> None:
        """Test case for list_shipment_methods

        List Shipment Methods
        """
        pass

    def test_set_shipments(self) -> None:
        """Test case for set_shipments

        Set Shipments
        """
        pass


if __name__ == '__main__':
    unittest.main()
