# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cart.models.cart_product_configuration_selection_option import CartProductConfigurationSelectionOption

class TestCartProductConfigurationSelectionOption(unittest.TestCase):
    """CartProductConfigurationSelectionOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CartProductConfigurationSelectionOption:
        """Test CartProductConfigurationSelectionOption
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CartProductConfigurationSelectionOption`
        """
        model = CartProductConfigurationSelectionOption()
        if include_optional:
            return CartProductConfigurationSelectionOption(
                grn = '',
                quantity = 56
            )
        else:
            return CartProductConfigurationSelectionOption(
        )
        """

    def testCartProductConfigurationSelectionOption(self):
        """Test CartProductConfigurationSelectionOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
