# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cart.models.cart_sort_order import CartSortOrder

class TestCartSortOrder(unittest.TestCase):
    """CartSortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCartSortOrder(self):
        """Test CartSortOrder"""
        # inst = CartSortOrder()

if __name__ == '__main__':
    unittest.main()
