# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cart.models.cart_item_custom_price import CartItemCustomPrice

class TestCartItemCustomPrice(unittest.TestCase):
    """CartItemCustomPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CartItemCustomPrice:
        """Test CartItemCustomPrice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CartItemCustomPrice`
        """
        model = CartItemCustomPrice()
        if include_optional:
            return CartItemCustomPrice(
                price = cart.models.cart_money.cartMoney(
                    units = '', 
                    micros = 56, ),
                previous_price = cart.models.cart_money.cartMoney(
                    units = '', 
                    micros = 56, )
            )
        else:
            return CartItemCustomPrice(
        )
        """

    def testCartItemCustomPrice(self):
        """Test CartItemCustomPrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
