# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cart.api.cart_api import CartApi


class TestCartApi(unittest.TestCase):
    """CartApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CartApi()

    def tearDown(self) -> None:
        pass

    def test_cart_set_custom_price_on_items(self) -> None:
        """Test case for cart_set_custom_price_on_items

        """
        pass


if __name__ == '__main__':
    unittest.main()
