# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cart.api.payments_api import PaymentsApi


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentsApi()

    def tearDown(self) -> None:
        pass

    def test_list_payment_methods(self) -> None:
        """Test case for list_payment_methods

        List Payment Methods
        """
        pass

    def test_set_set_payments(self) -> None:
        """Test case for set_set_payments

        Set SetPayments
        """
        pass


if __name__ == '__main__':
    unittest.main()
