# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cart.models.list_carts_request_filter_cart_status import ListCartsRequestFilterCartStatus

class TestListCartsRequestFilterCartStatus(unittest.TestCase):
    """ListCartsRequestFilterCartStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListCartsRequestFilterCartStatus(self):
        """Test ListCartsRequestFilterCartStatus"""
        # inst = ListCartsRequestFilterCartStatus()

if __name__ == '__main__':
    unittest.main()
