# coding: utf-8

"""
    Cart Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from cart.models.cart_get_active_cart_by_customer_request import CartGetActiveCartByCustomerRequest

class TestCartGetActiveCartByCustomerRequest(unittest.TestCase):
    """CartGetActiveCartByCustomerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CartGetActiveCartByCustomerRequest:
        """Test CartGetActiveCartByCustomerRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CartGetActiveCartByCustomerRequest`
        """
        model = CartGetActiveCartByCustomerRequest()
        if include_optional:
            return CartGetActiveCartByCustomerRequest(
                tenant_id = '',
                customer_grn = '',
                channel = '',
                market = '',
                currency = 'XXX'
            )
        else:
            return CartGetActiveCartByCustomerRequest(
        )
        """

    def testCartGetActiveCartByCustomerRequest(self):
        """Test CartGetActiveCartByCustomerRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
